# Generated by Django 4.2.11 on 2024-03-28 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0006_alter_equipment_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="person",
            new_name="admin",
        ),
    ]
