# Generated by Django 4.2.11 on 2024-03-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0008_remove_itemtype_user_equipment_reservation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="type",
            field=models.CharField(
                choices=[
                    ("parttime", "Part time"),
                    ("fulltime", "Full time"),
                    ("visitor", "Visitor"),
                ],
                max_length=255,
            ),
        ),
    ]
