# Generated by Django 4.2.11 on 2024-03-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0003_itemmaker_item_itemtype_item_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="itemmaker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appOne.itemmaker",
            ),
        ),
    ]
