# Generated by Django 4.2.11 on 2024-03-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0004_item_itemmaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("person_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=17, verbose_name="phone number"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="appOne.person",
                    ),
                ),
            ],
            bases=("appOne.person",),
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="appOne.person",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("parttime", "Par time"),
                            ("fulltime", "Full time"),
                            ("visitor", "Visitor"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            bases=("appOne.person",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="appOne.person",
                    ),
                ),
                ("course", models.CharField(max_length=255)),
            ],
            bases=("appOne.person",),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_start_date", models.DateTimeField()),
                ("booking_end_date", models.DateTimeField()),
                ("alerts", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=255,
                    ),
                ),
                ("purpose", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="appOne.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("equipment_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_of_device", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="appOne/images/")),
                ("quantity", models.PositiveIntegerField()),
                ("audit", models.DateField()),
                ("device_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("comments", models.TextField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                ("onsite", models.BooleanField(default=True)),
                ("availability", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipments",
                        to="appOne.person",
                    ),
                ),
            ],
        ),
    ]
