# Generated by Django 4.2.11 on 2024-03-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0005_person_admin_staff_student_reservation_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipments",
                to="appOne.admin",
            ),
        ),
    ]
