# Generated by Django 4.2.11 on 2024-03-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0007_rename_person_equipment_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemtype",
            name="user",
        ),
        migrations.AddField(
            model_name="equipment",
            name="reservation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="appOne.reservation",
            ),
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="ItemMaker",
        ),
        migrations.DeleteModel(
            name="ItemType",
        ),
    ]
