# Generated by Django 4.2.11 on 2024-04-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0009_alter_staff_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="appOne.admin",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="appOne.reservation",
            ),
        ),
    ]
