# Generated by Django 4.2.3 on 2024-04-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_alter_reservation_status'),
        ('appOne', '0010_alter_equipment_admin_alter_equipment_reservation'),
    ]

    operations = [
    ]
