# Generated by Django 4.2.11 on 2024-04-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0011_remove_staff_person_ptr_remove_student_person_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="reservation",
        ),
        migrations.AddField(
            model_name="reservation",
            name="equipment",
            field=models.ManyToManyField(
                related_name="reservations", to="appOne.equipment"
            ),
        ),
    ]
