# Generated by Django 4.2.11 on 2024-04-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0012_remove_equipment_reservation_reservation_equipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="equipment",
        ),
        migrations.AddField(
            model_name="reservation",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="appOne.equipment",
            ),
        ),
    ]
