# Generated by Django 4.2.11 on 2024-04-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0013_remove_reservation_equipment_reservation_equipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="user",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="availability",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(max_length=17, verbose_name="Phone Number"),
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="equipment",
        ),
        migrations.CreateModel(
            name="ReservationEquipment",
            fields=[
                (
                    "reservationEquipmentID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appOne.equipment",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appOne.reservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="equipment",
            field=models.ManyToManyField(
                related_name="reservations",
                through="appOne.ReservationEquipment",
                to="appOne.equipment",
            ),
        ),
    ]
