# Generated by Django 4.2.11 on 2024-04-17 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "appOne",
            "0014_remove_reservation_user_alter_equipment_availability_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="equipment_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="person_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="reservation_id",
            new_name="id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="availability",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.CharField(max_length=17, verbose_name="phone number"),
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="equipment",
        ),
        migrations.DeleteModel(
            name="ReservationEquipment",
        ),
        migrations.AddField(
            model_name="reservation",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="appOne.equipment",
            ),
        ),
    ]
